spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
